version: '3.8'

services:
  skyress.api:
    build:
      context: .
      dockerfile: Skyress/Dockerfile
    image: skyressapi
    container_name: skyress
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
    networks:
      - skyress-network

networks:
  skyress-network:
    driver: bridge
